#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

use Dotenv\Dotenv;

defined('YII_DEBUG') or define('YII_DEBUG', true);


$composerAutoload = [
    __DIR__ . '/vendor/autoload.php', // in yii2-dev repo
    __DIR__ . '/../autoload.php', // installed as a composer binary
];
$vendorPath = null;
foreach ($composerAutoload as $autoload) {
    if (file_exists($autoload)) {
        require $autoload;
        $vendorPath = dirname($autoload);
        break;
    }
}

if (file_exists('.env')) {
    (new Dotenv(__DIR__))->load();
}

require __DIR__ . '/framework/Yii.php';

$config = require __DIR__ . '/src/commands/config/config.php';

if(file_exists(__DIR__ . '/config/db.php')) {
    $config['components']['db'] = require __DIR__ . '/config/db.php';
}

$application = new yii\console\Application($config);

if ($vendorPath !== null) {
    $application->setVendorPath($vendorPath);
}
$exitCode = $application->run();
exit($exitCode);
