<?php
/**
 * Created by andrey.
 * User: andrey
 * Date: 2019-08-13
 * Time: 11:54
 */

namespace common\components;


use Yii;
use yii\web\Response;

class Controller extends \yii\web\Controller
{
    /**
     * @param string $view
     * @param array $params
     * @return string|\yii\console\Response|Response
     */
    public function render($view, $params = [])
    {
        $response = Yii::$app->getResponse();
        $response->format = Response::FORMAT_HTML;
        $response->data = parent::render($view, $params);

        return $response;
//        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }

}